annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/kube-version: '>= v1.16.0-0 < v1.31.0-0'
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/rancher-version: '>= 2.9.0'
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/display-name: NeuVector UI Extension
  catalog.cattle.io/ui-extensions-version: '>= 2.0.1'
apiVersion: v2
appVersion: 1.0.0-rancher-2.9.0
description: NeuVector extension for Rancher Manager
name: neuvector-ui-ext
type: application
version: 1.0.0-rancher-2.9.0
icon: >-
  https://raw.githubusercontent.com/neuvector/manager-ext/main/pkg/neuvector-ui-ext/nv-icon.svg
