nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/kube-version: ">= v1.16.0-0 < v1.31.0-0"
    catalog.cattle.io/display-name: NeuVector UI Extension
    catalog.cattle.io/rancher-version: ">= 2.9.0"
    catalog.cattle.io/ui-extensions-version: ">= 2.0.1"
